### ISSUE TITLE
Multi-GPU Testing Support?

### ISSUE THREAD

**Issue by JiYuanFeng** [speedinghzl/pytorch-segmentation-toolbox#22]
Can this toolbox support the Multi-scale testing?

**Comment by JiYuanFeng** [comment]
Sorry ! I think I am wrong. actually i am wondering to know is the project support Multi-GPU testing?

**Comment by speedinghzl** [comment]
No, does not support. You are welcome to add a new feature to support Multi-GPU testing.

**Comment by aasharma90** [comment]
Hi @JiYuanFeng @speedinghzl , 

I've attempted to create one. But, please use it with caution, since I'm a newbie to PyTorch  and could've implemented it sub-optimally. 
https://www.dropbox.com/s/ryf1f4507z4a5w4/evaluate_multigpu.py?dl=0

ps: I've checked that it gives the same performance results as evaluate.py (i.e. with single gpu testing), and all the 4 GPUs were occupied (with BATCH_SIZE=4, and GPU_IDs='0,1,2,3')

**Comment by speedinghzl** [comment]
@aasharma90 Nice work!
